spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      fail-fast: true
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
      trace:
        enabled: true
