server:
  port: 8096

spring:
  application:
    name: moex-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      name: moex-service
      profile: default
      label: main
      fail-fast: true
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
      trace:
        enabled: true

feign:
  circuitbreaker:
    enabled: true

management:
  enabled-by-default: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.amoroz.moexservice: DEBUG

moex:
  url: http://iss.moex.com/iss/statistics/engines/futures/markets/indicativerates/securities
