server:
  port: 8100

spring:
  application:
    name: weather-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      name: weather-service
      profile: default
      label: main
      fail-fast: true
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
      trace:
        enabled: true

feign:
  circuitbreaker:
    enabled: true

management:
  enabled-by-default: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.amoroz.weatherservice: DEBUG

open-weather:
  url: http://api.openweathermap.org/data/2.5/weather
  lat: 60.0158551
  lon: 30.3685371
  units: metric
  appid: 07cb39d0d64307ac8862d0136a00bd0e
  #https://openweathermap.org/current
